#ifndef APP_SLOT_CONFIG_H
#define APP_SLOT_CONFIG_H

#include "boot_info_v3.h"

#define APP_CFG_SLOT_NAME            "APP2"
#define APP_CFG_APPLICATION_ADDRESS  0x08080000U
#define APP_CFG_VECTOR_OFFSET        0x00080000U
#define APP_CFG_RUNNING_PARTITION    BOOT_INFO_SLOT_APP2
#define APP_CFG_OTHER_PARTITION      BOOT_INFO_SLOT_APP1
#define APP_CFG_VERSION_SLOT_TAG     "APP2"

#endif
